codecov:
  require_ci_to_pass: yes
  disable_default_path_fixes: false

coverage:
  precision: 2
  round: down
  range: "10...100"

status:
  project: yes
  patch: yes
  changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
