version: "2.1"

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.4-browsers

yarn_cache: &yarn_cache
  keys:
    - node-deps-node18-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node18-

deploy_cache: &deploy_cache
  key: last-deploy-sha

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --frozen-lockfile --non-interactive

jobs:
  lint_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node18-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2.1
  pr_check:
    jobs:
      - lint_test
